# -*- coding: utf-8 -*-
"""ass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3VUe18BqHgEqk8u44itNeMnGnzfCF1Y
"""

# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('pattern-loops')
jovian.set_colab_id('1L3VUe18BqHgEqk8u44itNeMnGnzfCF1Y')

"""# ass

Use the "Run" button to execute the code.
"""

!pip install jovian --upgrade --quiet

import jovian

# Execute this to save new versions of the notebook
jovian.commit(project="ass")

"""# Que-1"""

for i in range (1,6):
    for j in range(1,i+1):
        print(j, end='')
    print()

for i in range (1,6):
    for j in range(1,i+1):
        print(i, end='')
    print()

i=0

while i<5:
    j=1
    i+=1
    while j<i+1:
        print(j, end='')
        j+=1
    print()

for i in range(1,6,):
    for j in range(1,i+1):
        print(j,end="")
    print()
for i in range(5,1,-1):
    for j in range(1,i):
        print(j,end="")
    print()

for i in range(6,1,-1):
    for j in range(1,i):
        print(j,end="")
    print()
for i in range(1,6):
    for j in range(1,i+1):
        print(j,end="")
    print()

for i in range(5,0,-1):
    for j in range(i,0,-1):                
        print(j,end="")
    print()
for i in range(1,6):
    for j in range(i,0,-1):
         print(j,end="")
    print()

#patten 6
for i in range(1,6):
    print(" "*(5-i),end='')
    for j in range(1,i+1):
        print(j,end=' ')
    print()

#pattern 7
for i in range(1,6):
    for j in range(5,i-1,-1):
           print(j,end="")
    print()

#pattern 8
for i in range (5,0,-1):
    for j in range(5,i-1,-1):
        print(j,end="")
    print()

#pattern 9
for i in range (6,0,-1):
    for j in range(1,i):
        print(j,end="")
    print()

for i in range (1,6):
    for j in range(i,6):
         print(j,end="")
    print()

for i in range (1,6):
    for j in range(i,6):
         print(j,end="")
    print()

#pattern 10
#r = int(input("enter no.of rows \n")) 
k = 1
for i in range(5):
    for j in range(0,i+1):
        print(k,end=" ")
        k=k+1  
    print()

k=1
i=1

while i<15:
    j=1
    while j<=i and k<=15:
        print(k,end=' ')
        k+=1
        j+=1
    i+=1
    print("")

#pattern 11
for i in range (1,6):
    for j in range (i,0,-1):
        print(j,end="")
    print()

#pattern12
n=int(input("Enter a no: "))
for i in range(1,n+1):#to print rows
    for j in range(1,i+1):#to print coloumns
        print(i, end=" ")
        i+=5
    print(" ")

#pattern 15
for i in range(5,0,-1):
    print(" "*(5-i),end='')
    for j in range(1,i+1):
        print(j,end=' ')
    print()

#pattern12
n=int(input("Enter a no: "))
for i in range(1,n+1):#to print rows
    for j in range(1,i+1):#to print coloumns
        print(i, end=" ")
        i+=5
    print(" ")

for i in range(1,6):
    for j in range(1,i+1):
        print(j,end=' ')
    for j in range(i-1,0,-1):
        print(j,end=' ')
    print()

#pattern 16
for i in range(1,6):
    print(" "*(5-i),end='')
    for j in range(1,i+1):
        print(j,end=' ')
    print()
for i in range(4,0,-1):
    print(" "*(5-i),end='')
    for j in range(1,i+1):
        print(j,end=' ')
    print()

i=1

while i<6:
    j=1
    while j<6 and j<=i :
        print(j,end=' ')
        
        j+=1
    i+=1
    
    print("")

i=ord('A')

while i<ord('F'):
    j=ord("A")
    while j<ord('F') and j<=i :
        print(chr(j),end=' ')
        
        
        j+=1
    i+=1
    
    print("")

n=int(input("Enter the no. of rows: "))
for i in range(1, n + 1):
    print(" "*(n-i),end='')
    c = 1   
    for j in range(1, i + 1): 
    
        print(c, end = " ")
        c = int(c * (i - j) / j)
    print(" ")

#pattern 17
for i in range(1,6):
    print(" "*i,end='')
    for j in range(i,6,):
        print(j,end=" ")
    print()
for i in range(6,1,-1):
    print(" "*(i-1),end='')
    for j in range(i-1,6):
        print(j,end=" ")
    print()

#pattern 17
for i in range(1,6):
    print(" "*i,end='')
    for j in range(i,6,):
        print(j,end=" ")
    print()
for i in range(6,1,-1):
    print(" "*(i-1),end='')
    for j in range(i-1,6):
        print(j,end=" ")
    print()

#pattern 19
for i in range (6,1,-1):
    print(" "*(i-1),end='')
    for j in range (i-1,6):
        print(j,end=" ")
    print()

#pattern 20
for i in range(1,6):
    print(" "*(5-i),end='')
    for j in range (1,i+1):
        print(j,end="")
    for j in range(i-1,0,-1):
        print(j,end="")
    print()

#pattern 21
for i in range(1,6):
    for j in range (1,i+1):
        print(j%2,end="")
    print()

#pattern 22
for i in range(1,6):
    for j in range(1,6):
        if i==j:
            print(j,end="")
        else:
            print(0,end="")

    print()

#pattern 23
for i in range (1,6):
    print("1"*(5-i),end='')
    for j in range (1,i+1):
        print(i,end="")
    print()

#pattern 24 
for i in range (1,6):
    for j in range (i,6):
        print(j,end="")
        
    for j in range(4,i-1,-1):
        print(j,end="")
    print()

#pattern 25
for i in range (1,6):
    print(" "*(5-i),end='')
    for j in range (i):
        print(i,end= " ")
    print()

#pattern 26
for i in range (6,1,-1):
    
    for j in range (i-1,6):
        print(j,end="")
    for j in range (1,i-1):
        print("5",end='')
    print()

#pattern 27
k=1
i=1
while i<15:
    j=1
    while j<=i and k<=15:
        print(k,end=' ')
        j+=1
        k+=1
    i+=1
    print(" ")

lines=7  
i=1  
  
while i<=lines:
    j=1  
    while j<=i:  
        temp=i*j  
        print(temp, end='', flush=True)  
        print(" ", end='', flush=True)  
        j=j+1  
    print("")  
    i=i+1

