# -*- coding: utf-8 -*-
"""ass23_3pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAOzworCnOJ5p4Mkv_rL22kwErqsx8Bm
"""

n_term=int(input("Enter a number of terms u have to print"))

n1 = 0
n2 = 1
count = 0

if n_term <= 0:
  print("This is not a valid range")

elif n_term == 1:
  print("fibonacii sequence up to",n_term)
  print(n1-1)

else:
  print("Fibonacii sequence of the number is:")
  while count < n_term:
    print(n1)
    n3 = n1 + n2
    n1 = n2
    n2 = n3
    count+=1

a = int (input("Enter a number"))
list1= []
b=0
c=1
for i in range (0,a):
  print(b,end=" ")
  x=b+c
  b=c
  c=x
  list1.append(i)
print("\n",list1)

var1 = int(input("Please enter the digit : "))

var2 = 0
var3 = 1
list1 = []

for i in range(0,var1+1):
  list1.append(var2)
  var4 = var2 + var3
  var2 = var3
  var3 = var4 
  
print(list1)

var5 = int(input("Enter the number  whcih you want to find : "))


if var5 in list1:
  print("Yes number is part of fibo series")
else:
  print("Sorry, number is not part of fibo")

rev=0
count=0
n = int(input("enter the number"))
temp=n


while n>0:
  rem=n%10
  rev=(rev*10)+rem
  n=n//10
print(rev)
if temp==rev:
  print("it is a palindrome")
else:
  print("its not palindrome")

count=0

for i in range (100,1001):
  temp=i
  rev=0
  while i>0:
    rem=i%10
    rev=(rev*10)+rem
    i=i//10

  if temp==rev:
    count+=1
    print("it is a palindrome",temp)
print(count)