# -*- coding: utf-8 -*-
"""assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18taesjIww-Gd1nMLtI9P0Mj10wP8FLeF
"""



"""1. Python program to interchange first and last elements in a list
Given a list, write a Python program to swap first and last element of the list.
Examples: 
Input : [12, 35, 9, 56, 24]
Output : [24, 35, 9, 56, 12]

Input : [1, 2, 3]

Output : [3, 2, 1]
 

"""

list=[12, 35, 9, 56, 24]
list[0],list[len(list)-1]=list[len(list)-1],list[0]
print(list)

list  = [1,3,4,6,7,8,9]
print(list)
frist = list.pop()
last = list.pop(0) 
list.append(last)
list.insert(0,frist)
print(list)

"""2. WAP to find length of list
The list is : [1, 4, 5, 7, 8]
Length of list is : 5
# New Section
"""

list =  [1, 4, 5, 7, 8]
c=0
for i in list :
  c+=1
print('total element in list are : ',c)

"""3. WAP to Check if element exists in list 

Checking if 4 exists in list : 
Element Exists


"""

list = [1, 4, 5, 7, 8]
c=0
for i in list:
  if i==4:
    c+=1
if c>0:
  print('Element Exists ! ')
else:
  print('element not exists ! ')

list = [1, 4, 5, 7, 8]
c=0
for i in list:
  if i==4:
    c+=1
c>0 ? print('Element Exists') : print('element not exist')

"""4. WAP to clear a list
before clear: [6, 0, 4, 1]
after clear: []

"""

list = [1, 4, 5, 7, 8]
print(list)
for i in range (len(list)-1,-1,-1):
  list.remove(list[i])
  #print (i)
print(list)

"""5. WAP to Reversing a List
Input : list = [10, 11, 12, 13, 14, 15]
Output : [15, 14, 13, 12, 11, 10]
 
Input : list = [4, 5, 6, 7, 8, 9]
Output : [9, 8, 7, 6, 5, 4]

"""

list = [4, 5, 6, 7, 8, 9] 
print(list)
print (list[::-1])

list = [4, 5, 6, 7, 8, 9] 
l2=[]
for i in range (len(list)-1,-1,-1):
  l2.append(list[i])
print(list)
print(l2)

list = [10, 11, 12, 13, 14, 15]
list.reverse()
print("Reverse list:",list)

"""6. Given a list of numbers, write a Python program to find the sum of all the elements in the list.
Example: 
 
Input: [12, 15, 3, 10]
Output: 40
 
Input: [17, 5, 3, 5]
Output: 30

"""

list =  [12, 15, 3, 10] 
sum=0
for i in list:
  sum+=i
print ('total sum  is : ',sum)

"""7. Given a list of numbers, the task is to write a Python program to find the second largest number in the given list.
Examples: 
Input: list1 = [10, 20, 4]
Output: 10
Input: list2 = [70, 11, 20, 4, 100]
Output: 70

"""

list = [70, 11, 20, 4, 100] 
l = list
l.remove(max(list))
print('second highest element is : ',max(l))

list = [70, 11, 20, 4, 100] 
l=sorted(list)
l=l[::-1]
print('second highest element is : ',l[1])

"""8. Given a list of integers, the task is to find N largest elements assuming size of list is greater than or equal o N.
Examples :
Input : [4, 5, 1, 2, 9] 
        N = 2
Output :  [9, 5]
 
Input : [81, 52, 45, 10, 3, 2, 96] 
        N = 3
Output : [81, 96, 52]

"""

list=[4, 5, 1, 2, 9]
n=2
l=sorted(list)
l.reverse()
l2=[]
for i in range (0,n):
  l2.append(l[i])
print(l2)

list= [81, 52, 45, 10, 3, 2, 96] 
l=sorted(list)
l2=[]
n=3
for i in range (0,n):
  l2.append(l.pop())
print(l2)

"""9. Given a list of numbers, write a Python program to remove multiple elements from a list based on the given condition.
Example: 
Input: [12, 15, 3, 10]
Output: Remove = [12, 3], New_List = [15, 10]
 
Input: [11, 5, 17, 18, 23, 50]
Output: Remove = [1:5], New_list = [11, 50]

"""

list = [11, 5, 17, 18, 23, 50]
remove = [11,5]
for i in remove:
  list.remove(i)
print(list)

l1 = [11, 5, 17, 18, 23, 50]
l=sorted(l1)
r= [1,5]
print(l1)
start=r[0]
end=r[1]
for i in range (start,end):
  l.remove(l1[i])
  #print(l1[i])
print(l)

"""10. Input : lst = [15, 6, 7, 10, 12, 20, 10, 28, 10]
         x = 10
Output : 3 
10 appears three times in given list.
 
Input : lst = [8, 6, 8, 10, 8, 20, 10, 8, 8]
        x = 16
Output : 0

"""

l= [8, 6, 8, 10, 8, 20, 10, 8, 8]
l.count(10)

l= [15, 6, 7, 10, 12, 20, 10, 28, 10]
x=10
c=0
for i in l:
  if i==x:
    c+=1
print(c)

"""11. Given a list of integers with duplicate elements in it. The task to generate another list, which contains only the duplicate elements. In simple words, the new list should contain the elements which appear more than one.
Examples : 
Input : list = [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
Output : output_list = [20, 30, -20, 60]
 
 
Input :  list = [-1, 1, -1, 8]
Output : output_list = [-1]

"""

list = [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
 list.(20)

list1 = [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
set1=set(list1)
list2=[]
for i in set1:
    c=0
    for j in list1:
        if i==j:
            c+=1
    if c>1:
        list2.append(i)

print(list2)

list1 = [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
list2=[]
for i in list1:
    a=list1.count(i)
    if a!=1:
        for j in range(a-1):
            list1.remove(i)
        list2.append(i)
print(list2)

list = [10, 20, 30, 20, 20, 30, 40, 50, -20, 60, 60, -20, -20]
#s=set(list)
b=[]
c=[]
for i in list:
    if i not in b:
        b.append(i)
    else:
        c.append(i)
print(set(c))

"""12. Python program to find Cumulative sum of a list
The problem statement asks to produce a new list whose i^{th} element will be equal to the sum of the (i + 1) elements.
Examples : 
 
Input : list = [10, 20, 30, 40, 50]
Output : [10, 30, 60, 100, 150]
 
Input : list = [4, 10, 15, 18, 20]
Output : [4, 14, 29, 47, 67]
 

"""

list = [10, 20, 30, 40, 50]
 l=[]
 a=0
 for i in range (len(list)):
   a+=list[i]
   l.append(a)
print(l)

list = [4, 10, 15, 18, 20]
 l=[]
 for i in range (len(list)):

  if i>0:
       l.append((list[i]+l[i-1]))
  else:
    l.append(list[i])
print(l)

"""13. Break a list into chunks of size N in Python
Input: [1, 2, 3, 4, 5,6, 7, 8, 9]
Output: [[1, 2, 3, 4], [5, 6, 7, 8], [9]]

"""

l=[1, 2, 3, 4, 5,6, 7, 8, 9]
n=4
l1=[]
for i in range (0,len(l),n):
  s=[]
  print(i)
  for j in range (i,i+n):
    if i+n <len(l):
      s.append(l[j])
    else:
      for k in range (i,len(l)):
        s.append(l[k])
      break
  l1.append(s)
l1

l1=[1, 2, 3, 4, 5,6, 7, 8, 9,10]
n=4
l2=[]
for i in range(0,len(l1),n):
    l4=l1[i:i+n]
    l2.append(l4)
    
print(l2)

"""14. Remove common elements from two list in Python
 

"""

list = [10, 20, 30, 40,50] 
l=sorted(list)
list2 = [4, 10, 15, 18, 20]
for i in l:
  if i in list2:
    list.remove(i)
    list2.remove(i)
print(list)
print(list2)

# wrong code
list = [10, 20, 30, 40, 50] 
l=list
list2 = [4, 10, 15, 18, 20]
for i in l:
  if i in list2:
    list.remove(i)
    list2.remove(i)
print(list)
print(list2)

list = [10, 20, 30, 40,50] 
l=sorted(list)
list2 = [4, 10, 15, 18, 20]
l2=sorted(list2)
for i in range(len(l)):
  for j in l2:
    if j-l[i]==0:
      list.remove(j)
      list2.remove(j)
print(list)
print(list2)

list = [10, 20, 30, 40,50]
print(list[::-1])
print(list[::-1])

s='elephant'
list = []
for i in s:
  list.append(i)
set=set(list)
for i in set:
  print(i,list.count(i))

a=[32,5,3,6,7,54,87]
def bs(a):
  b=len(a)-1
  for x in range(b):
    for y in range(b-x):
       if a[y]>a[y+1]:
         a[y],a[y+1]=a[y+1],a[y]
  return a
bs(a)

a=int(input())
f=0
s=1
if a<=0:
  print (a)
else:
  print(f,s,end=' ')
  for i in range(2,a):
    n=f+s
    print(n,end=' ')
    f,s=s,n

# wrong code
a=int(input("enter number"))
if a>1:
  for x in range(2,a):
    if(a%x)==0:
      print("not prime")
      break
    else:
      print("Prime")
else:
  print("not prime")

lst =[1,2,3,6,2,1,6,5,8,4,9,7,5,4,1,5]
lst2 = []

for i in lst:
  if i not in lst2:
    lst2.append(i)
print(lst2)

