# -*- coding: utf-8 -*-
"""Day5 String mam Assigbments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVD2jFdZH9vDUCfjAEXeayNJnzyLuNBf
"""

s="amar"

print(s)

s[2]

for i in s:
    print(i)

for i in range(len(s)):
    print("at",i,"we have:",s[i])

mar

w=input("Enter a word:")
for i in range(1,len(w)+1):
    print(w[:i])

w=input("Enter a word:")
for i in range(len(w),0,-1):
    print(w[:i])

"god "*107

for i in range(1,6):
    print("X"*i)

for i in range(5,0,-1):
    print("X"*i)

for i in range(1,6):
    print(" "*(6-i)," X"*i)

s1="amar"
s2='''panchal'''
s3='education'
s4=s1+s2+"."+s3
print(s4)

s="a"
ord(s)

chr(98)

s="tHIS IS exAmPlE"

s.title()#returned formatted string

s

s="this is is it will be is"
s.count("is")

s="amar"
s.center(30,"-")

s="he is doing this"
s.replace(" is "," was ")

s

s

s.split()

s2="c:\\amar\\phd\\project\\autopredict"

s2.split("\\")

# we can use < > <= >= == != with string

count=0
line=input("Enter a line to test:")
line=line.lower()
for element in line:
    if element=='a' or element=='e' or element=='i' or element=='o' or element=='u':
        count+=1
print("Total vowels are:",count)

line=input("Enter a line to test:")
print("Word count:",len(line.split()))

line=input("Enter a line to test:")
wordlist=line.split()
print(wordlist)
wordlist=wordlist[::-1]
print(wordlist)
rline=""
for word in wordlist:
    rline=rline+" "+word
    print("rline has:",rline)
print("Reverse line:",rline)

line=input("Enter a line to test:")
wordlist=line.split()
print(wordlist)
uwlist=sorted(set(wordlist))
print("Sorted Unique list has:",uwlist)
for word in uwlist:
    print(word,"-->",wordlist.count(word))

s="google.com"
print(s.split())
a=[]
for i in s:
  n=s.count(i)

  a.append([i,n])  

b=dict(a)
print(b)

a= ("google.com")
dict1={}
print('number',':',"counts")
for i in (a):
  b=a.count(i)
  dict1[i]=b
  
print(dict1)

w=input("Enter a word:")
if len(w)>2:
  z=(w[:2])+(w[-2:])
  print(z)

elif len(w)<2:
  print("Empty")

a=input("Enter the string")
if len(a)<3:
  print(a)
elif a[-3:]=="ing":
  print(a+"ing")
else:
  print(a+"ing")

s="the lyrics is not that poor!"
v=s.find("not")
w=s.find("poor")
if v<w:
  print("the lyrics is good")
else:
  print("the lyrics is poor")



s="the lyrics is not that poor!"
s.replace("not that poor","good")

line=input("Enter a line to test:")

for i in range(len(line)):
    if i % 2 == 0:
      line[::2])

